CREATE TABLE IF NOT EXISTS account (
    id_account INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS product (
    id_product INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(30) NOT NULL,
    price INT NOT NULL,
    description VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS product_comment (
    id_comment INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_account INT NOT NULL,
    id_product INT NOT NULL,
    comment VARCHAR NOT NULL,
    PRIMARY KEY (id_comment, id_account, id_product),
    CONSTRAINT FK_product_comment_account FOREIGN KEY (id_account)
    REFERENCES account(id_account)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT FK_product_comment_product FOREIGN KEY (id_product)
    REFERENCES product(id_product)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
